version: 2.1
description: Automaticly build and push to Wiki

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Configure user
          command: |
            git config --global user.email "${GITHUB_EMAIL}"
            git config --global user.name "${GITHUB_USERNAME}"
      - run:
          name: Clone wiki repo
          command: |
            git clone https://${GITHUB_API_KEY}@github.com/RockSolidProject/WebApp.wiki.git wiki
      - run:
          name: Replace wiki files 
          command: |
            shopt -s extglob
            cp -r !(wiki) wiki/
      - run:
          name: Update remote 
          command: |
            cd wiki
            git add .
            git commit -m "Added updates from WebApp-wiki" || echo "No changes to commit"
            git push origin master
      

workflows:
  main:
    jobs:
      - build:
        filters:
          branches:
            only: main