version: 2.1
description: Automaticly build and push to Wiki

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Push wiki to project wiki
          command: |
            git config user.email "${GITHUB_EMAIL}"
            git config user.name "${GITHUB_USERNAME}"
            git remote remove origin
            git remote add origin https://${GITHUB_API_KEY}@github.com/RockSolidProject/WebApp.wiki.git
            git push origin master

workflows:
  main:
    jobs:
      - build:
        filters:
          branches:
            only: main